# Legacy makefile for Linux systems
# No Husky support

BINDIR = /usr/local/bin
CFGDIR = /usr/local/etc
CC     = gcc
CFLAGS = -Wall -O3 -DCFGDIR=\"$(CFGDIR)\"

.o: %.c
	$(CC) -c $(CFLAGS) $*.c 

OBJFILES = \
 config.o \
 emailpkt.o \
 log.o \
 mime.o \
 receive.o \
 send.o

all: emailpkt

emailpkt: $(OBJFILES)
	$(CC) -o emailpkt $(OBJFILES)

install:
	install -s emailpkt $(BINDIR)

clean:
	-rm *.o

distclean: clean
	-rm emailpkt

